# Generated by Django 5.2 on 2025-05-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='max_accessible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='max_regular',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_type',
            field=models.CharField(choices=[('regular', 'Звичайне'), ('accessible', 'Для осіб з інвалідністю')], default='regular', max_length=20),
        ),
    ]
